import { ru } from "./ru";

export const en: typeof ru = {
  signIn: "Sign In",
  notMemberYet: "Not a member yet?",
  signUp: "Sign Up",
  name: "Name",
  username: "Username",
  phone: "Phone",
  create: "Create",
  contacts: "Contacts",
  contactsAdd: "Add",
  main: "Main page",
  email: "Email",
  password: "Password",
  test: "Testing task",
  agressor: "If you go in, you won't go out",
  agressor2: "Get your hands off the poor guy",
  passwordConfirmation: "Confirm password",
  firstName: "Name",
  confirmRules: "By confirming, you consent to the personal processing of your data",
  alreadySignedUp: "Already signed up?",
  signin: "Sign In",
  signup: "Sign Up",
  listUsers: "Users list",
  find: "Find",
  shown: "Shown",
  from: "from",
  loadMore: "Load more",
  requiredField: "This field is required",
  minimalSymbols: "Minimum number of characters",
  maximumSymbols: "Maximum number of characters",
  passwordsMatch: "Passwords must match",
  enterEmail: "Please, enter email",
  enterPhone: "Please enter a phone number",
  enterName: "Enter name",
  noUsers: "No users",
  noUsersOnRequest: "Nothing found for your request",
  successAdded: "User succesfully added",
  userExists: "User with this email exists",
};
