export const ru = {
  signIn: "Войти",
  signUp: "Зарегистрироваться",
  notMemberYet: "Еще не зарегистрировались?",
  name: "Имя",
  username: "Никнейм",
  phone: "Телефон",
  create: "Создать",
  contacts: "Контакты",
  contactsAdd: "Добавить",
  main: "Главная",
  email: "Email",
  password: "Пароль",
  test: "Тестовое задание",
  agressor: "Если войдешь, то уже не выйдешь",
  agressor2: "Убери руки бедолага",
  passwordConfirmation: "Подтвердите пароль",
  firstName: "Имя",
  confirmRules: "Подтвердив, вы согласитесь на персональную обработку ваших данных",
  alreadySignedUp: "Уже зарегистрированы?",
  signin: "Войти",
  signup: "Зарегистрироваться",
  listUsers: "Список пользователей",
  find: "Найти",
  shown: "Показано",
  from: "из",
  loadMore: "Загрузить еще",
  requiredField: "Данное поле является обязательным",
  minimalSymbols: "Минимальное количество символов",
  maximumSymbols: "Максимальное количество символов",
  passwordsMatch: "Пароли должны совпадать",
  enterEmail: "Пожалуйста, ввведите email",
  enterPhone: "Пожалуйста, ввведите номер телефона",
  enterName: "Введите имя",
  noUsers: "Пользователей нет",
  noUsersOnRequest: "По вашему запросу ничего не найдено",
};
