export const ru = {
  signIn: "Войти",
  signUp: "Зарегистрироваться",
  notMemberYet: "Еще не зарегистрировались?",
  name: "Имя",
  username: "Никнейм",
  phone: "Телефон",
  create: "Создать",
  contacts: "Контакты",
  contactsAdd: "Добавить",
  main: "Главная",
  email: "Email",
  password: "Пароль",
  test: "Тестовое задание",
  agressor: "Если войдешь, то уже не выйдешь",
  agressor2: "Убери руки бедолага",
  passwordConfirmation: "Подтвердите пароль",
  firstName: "Имя",
  confirmRules: "Подтвердив, вы согласитесь на персональную обработку ваших данных",
  alreadySignedUp: "Уже зарегистрированы?",
  signin: "Войти",
  signup: "Зарегистрироваться",
  listUsers: "Список пользователей",
};
